zuul:
  prefix: /api
  routes:
    CONSUMER-SERVICE:
      path: /consumerService/**
      url: http://localhost:8082
    PRODUCER-SERVICE:
      path: /prodcucerService/**
      url: http://localhost:8081
server:
  port: 8080
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      instance: localhost
spring:
    application:
      name: zuul-service